server:
  port: 8083
spring:
  datasource:
    url: jdbc:h2:mem:auditdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
